### ISSUE TITLE
file is not included in action package when specified in app.config.yaml

### ISSUE THREAD

**Issue by deepakgarg1986** [adobe/aio-cli#356]
### Expected Behaviour
Trying to include a json . I expected this json file is zipped and inserted inside dist folder

### Actual Behaviour
Fill is not included in dist folder

### Reproduce Scenario (including but not limited to)
I am using windows machine.

#### Steps to Reproduce
1) I have following path in `app.config.yaml` file
```yaml
 get-google-token:
            function: actions/get-google-token/index.js
            include: 
                - ['C:\Users\deepak.garg\TSGConversion\tsg-conversion-web-events\actions\get-google-tokengoogle-credentials.json','test']
            runtime: 'nodejs:14'
```

#### Environment Info
```
  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 3.30 GB / 15.74 GB
  Binaries:
    Node: 16.13.0
    Yarn: Not Found
    npm: 8.1.0
  Virtualization:
    Docker: Not Found
  npmGlobalPackages:
    @adobe/aio-cli: Not Found
```
#### Sample Code that illustrates the problem
```yaml
application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      __APP_PACKAGE__:
        license: Apache-2.0
        actions:
          conversion-events-queue:
            function: actions/conversion-events-queue/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
              APF_DEV_KEY: $APF_DEV_KEY
            limits:
              concurrency: 500
            annotations:
              final: true
          send-message:
            function: actions/send-message/index.js
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
            annotations:
              final: true
          test-payload:
            function: actions/test-payload/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
            annotations:
              final: true
          upload-file:
            function: actions/upload-file/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
              sasURL: $SAS
              FILE_PATH: $RETRY_FILE_PATH
              FILE_NAME: $RETRY_FILE_NAME
            annotations:
              final: true
          get-google-token:
            function: actions/get-google-token/index.js
            include: 
                - ['C:\Users\deepak.garg\TSGConversion\tsg-conversion-web-events\actions\get-google-tokengoogle-credentials.json','test']
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
              KEY_FILE: $GCM360_KEY_FILE
            annotations:
              final: true
          update-state:
            function: actions/misc/updateAIOState.js
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
              key: google-token
              value: test
              ttl: 60
            annotations:
              final: true
```

**Comment by aiojbot** [comment]
JIRA issue created: https://jira.corp.adobe.com/browse/ACNA-1642

**Comment by shazron** [comment]
Note: this works on macOS, not on Windows

**Comment by waldo795** [comment]
Hi team - this issue is blocking a fix from being deployed into production which is currently blocking the customers data from being routed to the third party destination (Google in this case). The customer are close to raising a P1 for this issue, is there a way we can get support from someone with a MacOS device to help us work around this deployment?

**Comment by purplecabbage** [comment]
This has been fixed. You should be able to use a relative path now.
```
get-google-token:
    function: actions/get-google-token/index.js
    include: 
      - ['actions/get-google-token/google-credentials.json','test']
```
            
`npm i -g @adobe/aio-cli` to get the latest
