### ISSUE TITLE
Hello All, Can someone share manifest.yml with dummy values

### ISSUE THREAD

**Issue by giribabugalla** [adobe/aio-cli#383]

**Comment by giribabugalla** [comment]
Can someone provide manifest.yml and aio app:add:action is not working for me.

**Comment by purplecabbage** [comment]
```
packages:
  package-name:
    actions:
      action-name:
        function: actions/some-path/index.js
        web: 'yes'
        runtime: nodejs:16
        inputs:
          LOG_LEVEL: debug
          SOME_VAR: "passed as a param when your action is invoked"
        annotations:
          require-adobe-auth: false
          final: true
        include:
          - ['views/*.pug', 'views/']
          - ['public/', 'public/']

```

App Builder and Runtime tooling use the same format as OpenWhisk, except that it can live as part of an app.config.yaml or ext.config.yaml
https://developer.adobe.com/app-builder/docs/guides/configuration/

OpenWhisk examples here:
https://github.com/apache/openwhisk-wskdeploy/blob/master/docs/wskdeploy_inputs.md
