### ISSUE TITLE
Remove default license from app templates

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-cli#389]
What does it mean to add the yaml 'license: Apache-2.0' to ext.config.yaml?
This is the default that gets added to every new dx-excshell extension:
```
runtimeManifest:
  packages:
    dx-excshell-1:
      license: Apache-2.0
```

I have no idea what this even means? My manifest is open-source? What about the rest of my project?  I don't get a default license in package.json ... This just looks sloppy and should be removed.
