### ISSUE TITLE
web actions and web sequences with the same name can be deployed, web action implementation is unreachable

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli#614]
## Actual

You are able to deploy a web action and web sequence with the same name, and they have the same web url, listed twice.
The web url listed is effectively only the web sequence implementation, the web action implementation is unreachable.

## Expected

You should **not** be able to deploy a web action and web sequence with the same name, and the aio-cli should throw an error for this case.

## Sample Manifest

```yaml
runtimeManifest:
  packages:
    mypackage:
      sequences:
        foo:
          actions: bar, baz
          web: true
      actions:
        foo:
          function: actions/foo/index.js
          web: true
        bar:
          function: actions/bar/index.js
          web: true
        baz:
          function: actions/baz/index.js
          web: true
```
