### ISSUE TITLE
aio app dev handles not mapped inputs a $<INPUT_NAME>

### ISSUE THREAD

**Issue by rojoangel** [adobe/aio-cli#750]
### Expected Behaviour
If my runtime action declares inputs mapped to environment vars in the app.config.yaml
```yaml
created:
  function: created/index.js
  web: 'no'
  runtime: nodejs:20
  inputs:
    ONE_INPUT: $ONE_INPUT 
```
and the ONE_INPUT environment var is **not defined**

When running `aio app dev` the runtime action receives a ONE_INPUT param initialized with an empty string.

### Actual Behaviour

When running `aio app dev` the runtime action receives a ONE_INPUT param initialized with the $ONE_INPUT string.

#### Steps to Reproduce

If my runtime action declares inputs mapped to environment vars in the app.config.yaml

```yaml
created:
  function: created/index.js
  web: 'no'
  runtime: nodejs:20
  inputs:
    ONE_INPUT: $ONE_INPUT 
```
and the ONE_INPUT environment var is not defined

* when running aio app dev the runtime action receives a ONE_INPUT param initialized with the $ONE_INPUT string.
* when the runtime action is deployed and executed, it receives a ONE_INPUT param initialized with an empty string.
Would it be possible to have a consistent behavior when running aio app dev?

#### Environment Info
```
  System:
    OS: macOS 15.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.94 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    Yarn: Not Found
    npm: 10.9.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
  Virtualization:
    Docker: 27.4.0 - /usr/local/bin/docker
  npmGlobalPackages:
    @adobe/aio-cli: 10.3.4
```
